name: Lighthouse CI cds
on:
  push:
  schedule:
    - cron: '0 */8 * * *'
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: |
            https://corsi.unibo.it/magistrale/aegi
            https://corsi.unibo.it/1cycle/EconomicsPoliticsSocialSciences
            https://corsi.unibo.it/2cycle/AutomotiveEngineering
          budgetPath: .github/lighthouse/bad.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
